apiVersion: v1
kind: Service
metadata:
  name: task-management-service
  namespace: task-management
  labels:
    app: task-management
spec:
  type: NodePort
  selector:
    app: task-management
  ports:
  - name: frontend
    port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  - name: backend
    port: 8082
    targetPort: 8082
    nodePort: 30082
    protocol: TCP
